# Generated by Django 5.1.4 on 2024-12-26 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_options_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_staus',
            new_name='payment_status',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.order'),
        ),
    ]
