# Generated by Django 5.1.3 on 2024-11-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizza_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
