# Generated by Django 5.1.3 on 2024-11-24 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('pizza', '0004_alter_pizza_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile_photo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrecords',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='orderrecords',
            name='pizza_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pizza.pizza'),
        ),
    ]
