# Generated by Django 5.1.3 on 2024-11-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='photo',
            new_name='profile_photo',
        ),
    ]
