# Generated by Django 5.1.3 on 2024-11-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_orderrecords_final_price_orderrecords_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecords',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
